# Generated by Django 5.2.7 on 2025-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hash',
            field=models.CharField(default=1, editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
