# Generated by Django 5.2.7 on 2025-10-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('group', 'Group'), ('supergroup', 'SuperGroup'), ('chat', 'Chat')], default='room', max_length=50),
        ),
    ]
